<p>Le présent avis de confidentialité de Ferratec Technics AG ("Société", "nous", "notre" ou "nos") décrit comment et pourquoi nous pouvons collecter, stocker, utiliser et/ou partager ("traiter") vos informations lorsque vous utilisez nos services ("Services"), par exemple lorsque vous :</p>
<ul>
  <li>
    <p>visitez notre site web steckdosen-kombination.ch, ou tout autre site web qui renvoie à la présente note d'information sur la protection de la vie privée</p>
  </li>
  <li>
    <p>vous entrez en contact avec nous par d'autres moyens, y compris les ventes, le marketing ou les événements</p>
  </li>
</ul>
<p><strong>Vous avez des questions ou des inquiétudes ? </strong>La lecture de cet avis de confidentialité vous aidera à comprendre vos droits et vos choix en matière de protection de la vie privée. Si vous n'êtes pas d'accord avec nos politiques et pratiques, veuillez ne pas utiliser nos services. Si vous avez encore des questions ou des inquiétudes, veuillez nous contacter à l'adresse  <a href="mailto:info@ferratec.ch">info@ferratec.ch</a>.</p>
<h2>Résumé et points clés</h2>
<p>Ce résumé présente les points clés de notre avis de confidentialité, mais vous pouvez obtenir plus de détails sur chacun de ces sujets en cliquant sur le lien qui suit chaque point clé ou en utilisant notre table des matières ci-dessous pour trouver la section que vous recherchez.</p>
<p>Quelles informations personnelles traitons-nous ? Lorsque vous visitez, utilisez ou naviguez sur nos services, nous pouvons traiter des informations personnelles en fonction de la manière dont vous interagissez avec Ferratec Technics AG et les services, des choix que vous faites et des produits et fonctionnalités que vous utilisez. En savoir plus sur les informations personnelles que vous nous communiquez.</p>
<p>Traitons-nous des informations personnelles sensibles ? Nous ne traitons pas d'informations personnelles sensibles.</p>
<p>Recevons-nous des informations de la part de tiers ? Nous ne recevons aucune information de la part de tiers.</p>
<p><strong>Comment traitons-nous les informations ?</strong> Nous traitons vos informations afin de fournir, d'améliorer et d'administrer nos services, de communiquer avec vous, d'assurer la sécurité et la prévention des fraudes et de nous conformer à la loi. Nous pouvons également traiter vos informations à d'autres fins avec votre consentement. Nous ne traitons vos informations que si nous avons une raison légale valable de le faire. En savoir plus sur la manière dont nous traitons vos informations.</p>
<p><strong>Dans quelles situations et avec quelles parties partageons-nous les informations personnelles </strong>? Nous pouvons partager des informations dans des situations spécifiques et avec des tiers spécifiques. Découvrez quand et avec qui nous partageons vos informations personnelles.</p>
<p><strong>Comment assurons-nous la sécurité de vos informations ? </strong>Nous avons mis en place des processus et des procédures organisationnels et techniques pour protéger vos informations personnelles. Nous ne pouvons donc pas promettre ou garantir que des pirates informatiques, des cybercriminels ou d'autres tiers non autorisés ne seront pas en mesure de déjouer notre sécurité et de collecter, d'accéder, de voler ou de modifier vos informations de manière inappropriée. En savoir plus sur la façon dont nous protégeons vos information.</p>
<p><strong>Quels sont vos droits ?</strong> En fonction de votre situation géographique, la législation applicable en matière de protection de la vie privée peut vous conférer certains droits concernant vos informations personnelles. En savoir plus sur vos droits en matière de protection de la vie privée.</p>
<p><strong>Comment exercer vos droits ? </strong>La manière la plus simple d'exercer vos droits est de visiter le site steckdosen-kombination.ch, ou de nous contacter. Nous examinerons toute demande et y donnerons suite conformément aux lois applicables en matière de protection des données<strong>.</strong></p>
<p>Vous voulez en savoir plus sur ce que fait steckdosen-kombination.ch avec les informations que nous recueillons ? Consultez l'avis de confidentialité dans son intégralité.</p>
<h2>Quelles sont les informations que nous recueillons</h2>
<p>Nous recueillons les informations personnelles que vous nous fournissez volontairement lorsque vous vous inscrivez sur le service, lorsque vous souhaitez obtenir des informations sur nous et nos produits et services, lorsque vous participez à des activités sur le service ou lorsque vous nous contactez.</p>
<p><strong>Informations personnelles fournies par vous</strong><br>Les informations personnelles que nous recueillons dépendent du contexte de vos interactions avec nous et les services, des choix que vous faites et du produit et des fonctions que vous utilisez.</p>
<p><strong>Informations sensibles</strong><br>Nous ne traitons pas d'informations sensibles. Toutes les informations personnelles que vous nous fournissez doivent être vraies, complètes et exactes, et vous devez nous informer de toute modification de ces informations personnelles.</p>
<p><strong>Informations collectées automatiquement</strong><br>Nous recueillons automatiquement certaines informations lorsque vous visitez, utilisez ou naviguez sur les services. Ces informations ne révèlent pas votre identité spécifique (comme votre nom ou vos coordonnées), mais vous pouvez inclure des informations relatives à l'appareil ou à l'utilisation, comme les adresses IP, les caractéristiques du navigateur ou de l'appareil, le système d'exploitation, les préférences linguistiques, les URL de référence. Nom de l'appareil, pays, localisation, informations sur la manière et le moment où vous utilisez nos services et autres informations techniques. Ces informations sont principalement nécessaires pour maintenir la sécurité et le fonctionnement de nos services, ainsi qu'à des fins d'analyse et de reporting internes.</p>
<p>Comme de nombreuses entreprises, nous collectons également des informations par le biais de cookies et de technologies similaires.</p>
<p>Les informations que nous recueillons sont les suivantes</p>
<p>Données relatives à l'appareil. Nous collectons des données sur les appareils, telles que des informations sur votre ordinateur, votre téléphone, votre tablette ou tout autre appareil que vous utilisez pour accéder aux services. En fonction de l'appareil utilisé, ces données peuvent inclure des informations telles que l'adresse IP (ou le serveur proxy), les numéros d'identification de l'appareil et de l'application, la localisation, le type de navigateur, le modèle de matériel, le fournisseur d'accès à Internet et/ou l'opérateur mobile, le système d'exploitation et les informations relatives à la configuration du système.</p>
<p>Données de localisation. Nous collectons des données de localisation telles que des informations sur l'emplacement de votre appareil, qui peuvent être précises ou imprécises. La quantité d'informations collectées dépend du type et des paramètres de l'appareil que vous utilisez pour accéder aux services. Par exemple, nous pouvons utiliser le GPS et d'autres technologies pour collecter des données de géolocalisation qui nous indiquent votre emplacement actuel (sur la base de votre adresse IP). Vous pouvez choisir de ne pas nous autoriser à collecter ces informations, soit en refusant l'accès à ces informations, soit en désactivant les paramètres de localisation de votre appareil. Toutefois, si vous choisissez de vous désengager, il se peut que vous ne puissiez pas utiliser certains aspects des services.</p>
<h2>Comment traitons-nous vos informations ?</h2>
<p>Nous traitons vos informations personnelles pour diverses raisons, en fonction de la manière dont vous interagissez avec nos services, notamment :</p>
<ul>
  <li>
    <p>Faciliter la création et l'authentification des comptes et gérer les comptes d'utilisateurs. Nous pouvons traiter vos informations afin que vous puissiez créer votre compte et vous y connecter, ainsi que pour maintenir votre compte en bon état de fonctionnement.</p>
  </li>
  <li>
    <p>Fournir et faciliter la fourniture de services à l'utilisateur. Nous pouvons traiter vos informations pour vous fournir le service demandé.</p>
  </li>
  <li>
    <p>Pour vous envoyer des informations administratives. Nous pouvons traiter vos informations pour vous envoyer des détails sur nos produits et services, des modifications de nos conditions et politiques, et d'autres informations similaires.</p>
  </li>
  <li>
    <p>Sauvegarder ou protéger les intérêts vitaux d'une personne. Nous pouvons traiter vos informations lorsque cela est nécessaire pour sauver ou protéger l'intérêt vital d'une personne, par exemple pour prévenir un préjudice.</p>
  </li>
</ul>
<h2>Sur quelles bases juridiques nous appuyons-nous pour traiter vos informations ?</h2>
<p>Le règlement général sur la protection des données (RGPD) et la nouvelle loi fédérale sur la protection des données (nFADP) nous obligent à expliquer les bases juridiques valables sur lesquelles nous nous appuyons pour traiter vos informations personnelles. Ainsi, nous pouvons nous appuyer sur les bases juridiques suivantes pour traiter vos informations personnelles :</p>
<p><strong>Consentement</strong><br>Nous traitons vos informations si vous nous avez donné la permission (c'est-à-dire le consentement) d'utiliser vos informations personnelles à des fins spécifiques. Vous pouvez retirer votre consentement à tout moment. En savoir plus sur le retrait du consentement.</p>
<p><strong>Exécution d'un contrat</strong><br>Nous pouvons traiter vos informations personnelles lorsque nous estimons que cela est nécessaire pour remplir nos obligations contractuelles à votre égard, y compris la fourniture de nos services à votre demande avant de conclure un contrat avec vous.</p>
<p><strong>Obligation légale</strong><br>Nous pouvons traiter vos informations lorsque nous estimons que cela est nécessaire pour nous conformer à nos obligations légales, telles que la collaboration avec un organisme chargé de l'application de la loi ou un organisme de réglementation, l'exercice ou la défense de nos droits légaux, ou la divulgation de vos informations à titre de preuve dans le cadre d'un litige dans lequel nous sommes impliqués.</p>
<p><strong>Intérêts vitaux</strong><br>Nous pouvons traiter vos informations lorsque nous estimons qu'il est nécessaire de protéger vos intérêts vitaux ou les intérêts vitaux d'un tiers, par exemple dans des situations impliquant des menaces potentielles pour la sécurité d'une personne.</p>
<h2>QUAND ET AVEC QUI PARTAGEONS-NOUS VOS INFORMATIONS PERSONNELLES ?</h2>
<p>Nous pouvons être amenés à partager vos informations personnelles dans les situations suivantes:</p>
<ul>
  <li>
    <p><strong>Transferts d'entreprise</strong><br>Nous pouvons partager ou transférer vos informations dans le cadre d'une fusion, d'une vente d'actifs de la société, d'un financement ou d'une acquisition de tout ou partie de nos activités à une autre société, ou pendant les négociations relatives à une telle opération.</p>
  </li>
</ul>
<h2>Utilisons-nous des cookies et d'autres technologies de suivi ?</h2>
<p>Nous pouvons utiliser des cookies et des technologies de suivi similaires (comme les balises web et les pixels) pour accéder à des informations ou les stocker. Des informations spécifiques sur la manière dont nous utilisons ces technologies et sur la manière dont vous pouvez refuser certains cookies figurent dans notre avis sur les cookies.</p>
<h2>Combien de temps conservons-nous vos informations ?</h2>
<p>Nous conserverons vos informations personnelles aussi longtemps que nécessaire pour atteindre les objectifs définis dans le présent avis de confidentialité, à moins qu'une période de conservation plus longue ne soit requise ou autorisée par la loi (par exemple pour des raisons fiscales, comptables ou d'autres exigences légales). Aucune des finalités énoncées dans le présent avis n'exige que nous conservions vos informations personnelles plus longtemps que la période pendant laquelle les utilisateurs disposent d'un compte chez nous.</p>
<p>Lorsque nous n'avons plus de besoin commercial légitime de traiter vos informations personnelles, nous les supprimons ou les rendons anonymes ou, si cela n'est pas possible (par exemple, parce que vos informations personnelles ont été stockées dans des archives de sauvegarde), nous les stockons en toute sécurité et les isolons de tout traitement ultérieur jusqu'à ce qu'il soit possible de les supprimer.</p>
<h2>Comment assurons-nous la sécurité de vos informations ?</h2>
<p>Nous avons mis en œuvre des mesures de sécurité techniques et organisationnelles appropriées et raisonnables conçues pour protéger la sécurité de toutes les informations personnelles que nous traitons. Toutefois, malgré nos mesures de protection et nos efforts pour sécuriser les informations, aucune transmission électronique sur l'internet ou technologie de stockage des informations ne peut être garantie à 100 %, de sorte que nous ne pouvons pas promettre ou garantir que les pirates informatiques, les cybercriminels ou d'autres tiers non autorisés ne seront pas en mesure de déjouer notre sécurité et de collecter, d'accéder, de voler ou de modifier vos informations de manière inappropriée. Bien que nous fassions de notre mieux pour protéger vos informations personnelles, la transmission d'informations personnelles vers et à partir de nos services se fait à vos propres risques. Vous ne devez accéder aux services que dans un environnement sécurisé.</p>
<h2>Recueillons-nous des informations sur les mineurs ?</h2>

<p>Nous ne sollicitons pas sciemment de données auprès d'enfants de moins de 18 ans et nous ne commercialisons pas nos services auprès d'eux. En utilisant les services, vous déclarez avoir au moins 18 ans. Si nous apprenons que des informations personnelles ont été collectées auprès d'utilisateurs de moins de 18 ans, nous désactiverons le compte et prendrons des mesures raisonnables pour supprimer rapidement ces données de nos registres. Si vous avez connaissance de données que nous aurions pu collecter auprès d'enfants de moins de 18 ans, veuillez nous contacter à l'adresse suivante :  <a href="mailto:info@ferratec.ch">info@ferratec.ch</a></p>
<h2>Quels sont vos droits en matière de protection de la vie privée ?</h2>
<p>Dans certaines régions (comme l'EEE et le Royaume-Uni), vous disposez de certains droits en vertu des lois applicables en matière de protection des données. Il peut s'agir du droit (i) de demander l'accès aux informations personnelles et d'en obtenir une copie, (ii) de demander la rectification ou l'effacement, (iii) de restreindre le traitement de vos informations personnelles et (iv), le cas échéant, de demander la portabilité des données. Dans certaines circonstances, vous pouvez également avoir le droit de vous opposer au traitement de vos informations personnelles. Vous pouvez formuler une telle demande en nous contactant à l'aide des coordonnées indiquées dans la section "COMMENT PEUT-ON NOUS CONTACTER AU SUJET DE LA PRÉSENTE NOTICE" ci-dessous.</p>
<p>Nous examinerons toute demande et y donnerons suite conformément aux lois applicables en matière de protection des données.</p>
<p>Si vous êtes situé dans l'EEE ou au Royaume-Uni et que vous pensez que nous traitons illégalement vos informations personnelles, vous avez également le droit de déposer une plainte auprès de l'autorité de protection des données de votre État membre ou de l'autorité de protection des données du Royaume-Uni.</p>
<p>Si vous résidez en Suisse, vous pouvez contacter le commissaire fédéral à la protection des données et à l'information.</p>
<p><strong>Retrait du consentement :</strong> Si nous nous appuyons sur votre consentement pour traiter vos informations personnelles, vous avez le droit de retirer votre consentement à tout moment. Vous pouvez retirer votre consentement à tout moment en nous contactant à l'aide des coordonnées indiquées dans la section "COMMENT PEUT-ON NOUS CONTACTER AU SUJET DE CET AVIS ?" ci-dessous ou en mettant à jour vos préférences.</p>
<p>Toutefois, veuillez noter que cela n'affectera pas la légalité du traitement avant son retrait, ni le traitement de vos informations personnelles effectué sur la base de motifs de traitement légitimes autres que le consentement.</p>
<p><strong>Informations sur le compte</strong></p>
<p>Si vous souhaitez à tout moment revoir ou modifier les informations de votre compte ou mettre fin à votre compte, vous pouvez le faire :</p>
<ul>
  <li>
    <p>vous connecter aux paramètres de votre compte et mettre à jour votre compte d'utilisateur</p>
  </li>
</ul>
<p>Si vous demandez à fermer votre compte, nous désactiverons ou supprimerons votre compte et vos informations de nos bases de données actives. Toutefois, nous pouvons conserver certaines informations dans nos fichiers afin de prévenir la fraude, de résoudre des problèmes, de contribuer à des enquêtes, de faire respecter nos conditions légales et/ou de nous conformer à des exigences légales applicables.</p>
<p>Cookies et technologies similaires : La plupart des navigateurs Web sont configurés pour accepter les cookies par défaut. Si vous préférez, vous pouvez généralement choisir de configurer votre navigateur pour qu'il supprime les cookies et les rejette. Si vous choisissez de supprimer les cookies ou de les rejeter, cela pourrait affecter certaines fonctionnalités et certains services de nos services. Vous pouvez également choisir de ne pas recevoir de publicité basée sur l'intérêt de la part des annonceurs sur nos services.</p>
<h2>Formulaire de contrôle caractéristiques "Do-Not-Track"</h2>
<p>La plupart des navigateurs web et certains systèmes d'exploitation mobiles et applications mobiles comprennent une fonction ou un paramètre "Do-Not-Track" ("DNT") que vous pouvez activer pour signaler votre préférence en matière de respect de la vie privée, à savoir que les données relatives à vos activités de navigation en ligne ne soient pas surveillées et collectées. À ce stade, aucune norme technologique uniforme n'a été finalisée pour la reconnaissance et la mise en œuvre des signaux DNT. Par conséquent, nous ne répondons pas actuellement aux signaux DNT du navigateur ou à tout autre mécanisme qui communique automatiquement votre choix de ne pas être suivi en ligne. Si une norme de suivi en ligne est adoptée et que nous devons la suivre à l'avenir, nous vous informerons de cette pratique dans une version révisée du présent avis de confidentialité.</p>
<h2>Les résidents de Californie ont-ils des droits spécifiques en matière de protection de la Vie privée ?</h2>
<p>La section 1798.83 du code civil californien, également connue sous le nom de loi "Shine the light", permet à nos utilisateurs qui résident en Californie de nous demander et d'obtenir gratuitement, une fois par an, des informations sur les catégories d'informations personnelles (le cas échéant) que nous avons divulguées à des tiers à des fins de marketing direct, ainsi que le nom et l'adresse de tous les tiers avec lesquels nous avons partagé des informations personnelles au cours de l'année civile qui précède immédiatement. Si vous résidez en Californie et que vous souhaitez faire une telle demande, veuillez nous la soumettre par écrit en utilisant les coordonnées fournies ci-dessous.</p>
<p>Si vous avez moins de 18 ans, que vous résidez en Californie et que vous disposez d'un compte enregistré auprès des services, vous avez le droit de demander la suppression des données indésirables que vous publiez sur les services. Pour demander la suppression de ces données, veuillez nous contacter en utilisant les coordonnées indiquées ci-dessous et en indiquant l'adresse électronique associée à votre compte ainsi qu'une déclaration indiquant que vous résidez en Californie. Nous ferons en sorte que les données ne soient pas affichées publiquement sur les services, mais sachez que les données peuvent ne pas être complètement ou intégralement supprimées de tous nos systèmes (par exemple, sauvegardes, etc.).</p>
<h2>Le présent avis est-il mis à jour ?</h2>
<p>Nous pouvons mettre à jour cet avis de confidentialité de temps à autre. La version mise à jour sera indiquée par un La version mise à jour sera effective dès qu'elle sera accessible. Si nous apportons des modifications importantes au présent avis de confidentialité, nous vous en informerons soit en affichant de manière visible un avis de ces modifications, soit en vous envoyant directement une notification. Nous vous encourageons à consulter fréquemment le présent avis de confidentialité afin de vous tenir informé de la manière dont nous protégeons vos informations.</p>
<h2>Comment pouvez-vous nous contacter au sujet de cet avis ?</h2>
<p>Si vous avez des questions ou des commentaires sur le présent avis, vous pouvez nous envoyer un courriel à l'adresse info@ferratec.ch ou nous contacter par courrier à l'adresse suivante&nbsp;:</p>
<p>FERRATEC TECHNICS AG<br>Grossmattstrasse 19<br>8964 Rudolfstetten</p>
<h2>Comment pouvez-vous consulter, mettre à jour ou supprimer les données que nous collectons auprès de vous ?</h2>
<p>En vertu des lois applicables dans votre pays, vous pouvez avoir le droit de demander l'accès aux informations personnelles que nous recueillons auprès de vous, de modifier ces informations ou de les supprimer. Pour demander la révision, la mise à jour ou la suppression de vos informations personnelles, veuillez envoyer votre demande par courrier électronique : <a href="mailto:info@ferratec.ch">info@ferratec.ch</a></p>