
<p>Dieser Datenschutzhinweis der Ferratec Technics AG ("Unternehmen", "wir", "uns" oder "unser") beschreibt, wie und warum wir Ihre Daten erheben, speichern, nutzen und/oder weitergeben ("verarbeiten"), wenn Sie unsere Dienste ("Dienste") nutzen, z.B. wenn Sie:</p>
<ul>
  <li>unsere Website steckdosen-kombination.ch oder eine andere Website von uns besuchen, die auf diese Datenschutzerklärung verweist</li>
  <li>mit uns auf andere Weise in Kontakt treten, einschließlich Verkauf, Marketing oder Veranstaltungen</li>
</ul>
<p><strong>Haben Sie Fragen oder Bedenken?</strong> Die Lektüre dieses Datenschutzhinweises hilft Ihnen, Ihre Rechte und Möglichkeiten zum Schutz Ihrer Daten zu verstehen. Wenn Sie mit unseren Richtlinien und Praktiken nicht einverstanden sind, nutzen Sie unsere Dienste bitte nicht. Sollten Sie noch Fragen oder Bedenken haben, kontaktieren Sie uns bitte unter <a href="mailto:info@ferratec.ch" title="E-Mail senden">info@ferratec.ch</a>.</p>
<h2>Zusammenfassung und wichtige Punkte</h2>
<p>In dieser Zusammenfassung finden Sie die wichtigsten Punkte unserer Datenschutzerklärung. Sie können jedoch weitere Einzelheiten zu jedem dieser Themen erfahren, indem Sie auf den Link klicken, der auf jeden wichtigen Punkt folgt, oder indem Sie unser Inhaltsverzeichnis unten verwenden, um den Abschnitt zu finden, den Sie suchen.</p>
<p><strong>Welche personenbezogenen Daten verarbeiten wir?</strong><br>Wenn Sie unsere Dienste besuchen, nutzen oder durch sie navigieren, können wir personenbezogene Daten verarbeiten, je nachdem, wie Sie mit Ferratec Technics AG und den Diensten interagieren, welche Entscheidungen Sie treffen und welche Produkte und Funktionen Sie nutzen. Erfahren Sie mehr über die persönlichen Informationen, die Sie uns zur Verfügung stellen.</p>
<p><strong>Verarbeiten wir sensible persönliche Daten?</strong><br>Wir verarbeiten keine sensiblen persönlichen Daten.</p>
<p><strong>Erhalten wir irgendwelche Informationen von Dritten?</strong><br>Wir erhalten keine Informationen von Drittparteien.</p>
<p><strong>Wie verarbeiten wir Informationen?</strong><br>Wir verarbeiten Ihre Daten, um unsere Dienste bereitzustellen, zu verbessern und zu verwalten, um mit Ihnen zu kommunizieren, um Sicherheit und Betrug vorzubeugen und um gesetzliche Vorschriften einzuhalten. Mit Ihrer Zustimmung können wir Ihre Daten auch für andere Zwecke verarbeiten. Wir verarbeiten Ihre Daten nur, wenn wir einen gültigen rechtlichen Grund dafür haben. Erfahren Sie mehr darüber, wie wir Ihre Daten verarbeiten.</p>
<p><strong>In welchen Situationen und an welche Parteien geben wir personenbezogene Daten weiter?</strong><br>Wir können Informationen in bestimmten Situationen und mit bestimmten Dritten weitergeben. Erfahren Sie mehr darüber, wann und an wen wir Ihre personenbezogenen Daten weitergeben.</p>
<p><strong>Wie bewahren wir Ihre Daten sicher auf?</strong><br>Wir haben organisatorische und technische Prozesse und Verfahren eingerichtet, um Ihre persönlichen Daten zu schützen. Allerdings kann keine elektronische Übertragung über das Internet und keine Informationsspeicherungstechnologie zu 100 % sicher sein, so dass wir nicht versprechen oder garantieren können, dass Hacker, Cyberkriminelle oder andere unbefugte Dritte nicht in der Lage sind, unsere Sicherheit zu umgehen und Ihre Daten unrechtmäßig zu sammeln, darauf zuzugreifen, sie zu stehlen oder zu verändern. Erfahren Sie mehr darüber, wie wir Ihre Daten sicher halten.</p>
<p><strong>Welche Rechte haben Sie?</strong><br>Je nachdem, wo Sie sich geografisch befinden, haben Sie nach dem geltenden Datenschutzrecht bestimmte Rechte in Bezug auf Ihre personenbezogenen Daten. Erfahren Sie mehr über Ihre Datenschutzrechte.</p>
<p><strong>Wie können wir Ihre Rechte ausüben?</strong><br>Am einfachsten können Sie Ihre Rechte ausüben, indem Sie steckdosen-kombination.ch besuchen oder sich mit uns in Verbindung setzen. Wir werden jede Anfrage in Übereinstimmung mit den geltenden Datenschutzgesetzen prüfen und entsprechend handeln.</p>
<p>Möchten Sie mehr darüber erfahren, was steckdosen-kombination.ch mit den von uns erfassten Daten macht? Lesen Sie den vollständigen Datenschutzhinweis.</p>

<h2>Welche Informationen sammeln wir?</h2>
<p>Persönliche Informationen, die Sie uns zur Verfügung stellen. Die persönlichen Daten, die wir erfassen, hängen vom Kontext Ihrer Interaktionen mit uns und den Diensten, Ihren Entscheidungen und den von Ihnen verwendeten Produkten und Funktionen ab.</p>
<p><strong>Sensible Informationen</strong><br>Wir verarbeiten keine sensiblen Informationen. Alle personenbezogenen Daten, die Sie uns zur Verfügung stellen, müssen wahrheitsgemäß, vollständig und genau sein, und Sie müssen uns über alle Änderungen dieser personenbezogenen Daten informieren.</p>
<p><strong>Automatisch erfasste Informationen</strong><br>Einige Informationen - wie z. B. Ihre Internetprotokoll-Adresse (IP-Adresse) und/oder Browser- und Geräteeigenschaften - werden automatisch erfasst, wenn Sie unsere Dienste besuchen. Wir erfassen automatisch bestimmte Informationen, wenn Sie die Dienste besuchen, nutzen oder durch sie navigieren. Diese Informationen geben keinen Aufschluss über Ihre Identität (wie z. B. Ihren Namen oder Ihre Kontaktdaten), aber Sie können Geräte- oder Nutzungsinformationen enthalten, wie z. B. IP-Adressen, Browser- oder Geräteeigenschaften, Betriebssysteme, Spracheinstellungen, verweisende URLs. Gerätename, Land, Standort, Informationen darüber, wie und wann Sie unsere Dienste nutzen, und andere technische Informationen. Diese Informationen werden in erster Linie benötigt, um die Sicherheit und den Betrieb unserer Dienste aufrechtzuerhalten sowie für unsere internen Analyse- und Berichtszwecke.</p>
<p>Wie viele andere Unternehmen sammeln auch wir Daten durch Cookies und ähnliche Technologien. Die von uns gesammelten Informationen umfassen:</p>
<p><strong>Gerätedaten</strong><br>Wir erfassen Gerätedaten wie Informationen über Ihren Computer, Ihr Telefon, Ihr Tablet oder ein anderes Gerät, das Sie für den Zugriff auf die Dienste verwenden. Je nach verwendetem Gerät können diese Gerätedaten Informationen wie IP-Adresse (oder Proxy-Server), Geräte- und Anwendungs-Identifikationsnummern, Standort, Browsertyp, Hardwaremodell, Internetdienstanbieter und/oder Mobilfunkanbieter, Betriebssystem und Systemkonfigurationsinformationen enthalten.</p>
<p><strong>Standortdaten</strong><br>Wir erfassen Standortdaten, wie z. B. Informationen über den Standort Ihres Geräts, die entweder genau oder ungenau sein können. Wie viele Informationen wir erfassen, hängt von der Art und den Einstellungen des Geräts ab, das Sie für den Zugriff auf die Dienste verwenden. So können wir beispielsweise GPS und andere Technologien verwenden, um Geolokalisierungsdaten zu erfassen, die uns Ihren aktuellen Standort mitteilen (auf der Grundlage Ihrer IP-Adresse). Wenn Sie sich jedoch dagegen entscheiden, können Sie möglicherweise bestimmte Aspekte der Dienste nicht nutzen.</p>

<h2>Wie verarbeiten wir Ihre Informationen?</h2>
<p>Wir verarbeiten Ihre personenbezogenen Daten aus verschiedenen Gründen, je nachdem, wie Sie mit unseren Diensten interagieren, darunter:</p>

<ul>
  <li>Zur Erleichterung der Kontoerstellung und -authentifizierung und zur sonstigen Verwaltung von Benutzerkonten. Wir können Ihre Daten verarbeiten, damit Sie Ihr Konto erstellen und sich bei ihm anmelden können, und um Ihr Konto in Ordnung zu halten.
  <li>Zur Bereitstellung und Erleichterung der Bereitstellung von Dienstleistungen für den Nutzer. Wir können Ihre Daten verarbeiten, um Ihnen die angeforderte Dienstleistung zur Verfügung zu stellen.
  <li>Um Ihnen administrative Informationen zukommen zu lassen. Wir können Ihre Daten verarbeiten, um Ihnen Informationen über unsere Produkte und Dienstleistungen, Änderungen unserer Bedingungen und Richtlinien und ähnliche Informationen zukommen zu lassen.
  <li>Zur Wahrung oder zum Schutz der vitalen Interessen einer Person. Wir können Ihre Daten verarbeiten, wenn dies notwendig ist, um lebenswichtige Interessen einer Person zu wahren oder zu schützen, z. B. um Schaden abzuwenden.</li>
</ul>

<h2>Auf welche Rechtsgrundlagen stützen wir uns bei der Verarbeitung Ihrer Daten?</h2>
<p>Die allgemeine Datenschutzverordnung (GDPR) und das neue Bundesgesetz über den Datenschutz (nFADP) verpflichten uns, die gültigen Rechtsgrundlagen zu erläutern, auf die wir uns stützen, um Ihre persönlichen Daten zu verarbeiten. Demnach können wir uns auf die folgenden Rechtsgrundlagen stützen, um Ihre personenbezogenen Daten zu verarbeiten:</p>

<p><strong>Einwilligung</strong><br>Wir verarbeiten Ihre Daten, wenn Sie uns die Erlaubnis (d. h. Ihre Zustimmung) erteilt haben, Ihre personenbezogenen Daten für einen bestimmten Zweck zu verwenden. Sie können Ihre Einwilligung jederzeit widerrufen. Erfahren Sie mehr über die Rücknahme Ihrer Einwilligung.</p>
<p><strong>Erfüllung eines Vertrags</strong><br>Wir können Ihre personenbezogenen Daten verarbeiten, wenn wir der Meinung sind, dass dies notwendig ist, um unsere vertraglichen Verpflichtungen Ihnen gegenüber zu erfüllen, einschließlich der Bereitstellung unserer Dienste auf Ihre Anfrage hin, bevor wir einen Vertrag mit Ihnen abschließen.</p>
<p><strong>Gesetzliche Verpflichtung</strong><br>Wir können Ihre Daten verarbeiten, wenn wir der Meinung sind, dass dies für die Erfüllung unserer rechtlichen Verpflichtungen notwendig ist, wie z. B. die Zusammenarbeit mit einer Strafverfolgungsbehörde oder einer Aufsichtsbehörde, die Ausübung oder Verteidigung unserer gesetzlichen Rechte oder die Offenlegung Ihrer Daten als Beweismittel in einem Rechtsstreit, an dem wir beteiligt sind.</p>
<p><strong>Lebenswichtige Interessen</strong><br>Wir können Ihre Daten verarbeiten, wenn wir glauben, dass dies notwendig ist, um Ihre lebenswichtigen Interessen oder die lebenswichtigen Interessen Dritter zu schützen, z. B. in Situationen, in denen die Sicherheit einer Person bedroht ist.</p>
    
<h2>Wann und an wen geben wir Ihre personenbezogenen Daten weiter?</h2>
<p>In den folgenden Fällen müssen wir Ihre personenbezogenen Daten möglicherweise weitergeben:</p>
<ul>
  <li>Geschäftsübertragungen. Es kann sein, dass wir Ihre Daten in Verbindung mit oder während der Verhandlungen über eine Fusion, den Verkauf von Unternehmensvermögen, eine Finanzierung oder die Übernahme unseres gesamten oder eines Teils unseres Unternehmens durch ein anderes Unternehmen weitergeben oder übertragen.
</li>
</ul>

<h2>Verwenden wir Cookies und andere Tracking-Technologien?</h2>
<p>Wir können Cookies und ähnliche Tracking-Technologien (wie Web-Beacons und Pixel) verwenden, um auf Informationen zuzugreifen oder sie zu speichern. Spezifische Informationen darüber, wie wir solche Technologien verwenden und wie Sie bestimmte Cookies ablehnen können, finden Sie in unserem Cookie-Hinweis.</p>

<h2>Wie lange bewahren wir Ihre Informationen auf?</h2>
<p>Wir bewahren Ihre personenbezogenen Daten so lange auf, wie es für die in dieser Datenschutzerklärung dargelegten Zwecke erforderlich ist, es sei denn, eine längere Aufbewahrungsfrist ist gesetzlich vorgeschrieben oder zulässig (z. B. aus steuerlichen, buchhalterischen oder anderen rechtlichen Gründen). Keiner der in dieser Mitteilung genannten Zwecke erfordert es, dass wir Ihre personenbezogenen Daten länger aufbewahren als den Zeitraum, in dem die Nutzer ein Konto bei uns haben.</p>
<p>Wenn wir keine weitere legitime geschäftliche Notwendigkeit haben, Ihre personenbezogenen Daten zu verarbeiten, werden wir diese Daten entweder löschen oder anonymisieren, oder, falls dies nicht möglich ist (z. B. weil Ihre personenbezogenen Daten in Sicherungsarchiven gespeichert wurden), werden wir Ihre personenbezogenen Daten sicher aufbewahren und von der weiteren Verarbeitung isolieren, bis eine Löschung möglich ist.</p>

<h2>Wie halten wir Ihre Daten sicher?</h2>
<p>Wir haben geeignete und angemessene technische und organisatorische Sicherheitsmaßnahmen getroffen, um die Sicherheit der von uns verarbeiteten personenbezogenen Daten zu schützen. Trotz unserer Sicherheitsvorkehrungen und Bemühungen zum Schutz von Informationen kann jedoch keine elektronische Übertragung über das Internet oder Informationsspeicherungstechnologie zu 100 % sicher sein, so dass wir nicht versprechen oder garantieren können, dass Hacker, Cyberkriminelle oder andere unbefugte Dritte nicht in der Lage sind, unsere Sicherheit zu überwinden und Ihre Informationen unrechtmäßig zu sammeln, darauf zuzugreifen, zu stehlen oder zu ändern. Obwohl wir unser Bestes tun, um Ihre persönlichen Daten zu schützen, erfolgt die Übertragung von persönlichen Daten zu und von unseren Diensten auf Ihr eigenes Risiko. Sie sollten nur über eine sichere Umgebung auf die Dienste zugreifen.</p>

<h2>Sammeln wir Informationen von Minderjährigen?</h2>
<p>Wir bitten nicht wissentlich um Daten von Kindern unter 18 Jahren und vermarkten diese auch nicht an sie. Indem Sie die Dienste nutzen, erklären Sie, dass Sie mindestens 18 Jahre alt sind. Wenn wir erfahren, dass personenbezogene Daten von Nutzern unter 18 Jahren erfasst wurden, werden wir das Konto deaktivieren und angemessene Maßnahmen ergreifen, um diese Daten unverzüglich aus unseren Aufzeichnungen zu löschen. Wenn Sie von Daten erfahren, die wir von Kindern unter 18 Jahren gesammelt haben, wenden Sie sich bitte per E-Mail an: <a href="mailto:info@ferratec.ch" title="E-Mail senden">info@ferratec.ch</a></p>

<h2>Welche Rechte haben Sie in Bezug auf Ihre Privatsphäre?</h2>
<p>In einigen Regionen (wie dem EWR und dem Vereinigten Königreich) haben Sie nach den geltenden Datenschutzgesetzen bestimmte Rechte. Dazu gehören u. a. das Recht(i) auf Zugang und Erhalt einer Kopie Ihrer personenbezogenen Daten,(ii) auf Berichtigung oder Löschung,(iii) auf Einschränkung der Verarbeitung Ihrer personenbezogenen Daten und (iV) gegebenenfalls auf Datenübertragbarkeit. Unter bestimmten Umständen haben Sie auch das Recht, der Verarbeitung Ihrer personenbezogenen Daten zu widersprechen. Sie können einen solchen Antrag stellen, indem Sie sich mit uns in Verbindung setzen, indem Sie die Kontaktdaten im Abschnitt "WIE KÖNNEN SIE UNS ÜBER DIESEN HINWEIS KONTAKTIEREN?" unten verwenden.</p>
<p>Wir werden jeden Antrag in Übereinstimmung mit den geltenden Datenschutzgesetzen prüfen und entsprechend handeln.</p>
<p>Wenn Sie im EWR oder im Vereinigten Königreich ansässig sind und der Meinung sind, dass wir Ihre personenbezogenen Daten unrechtmäßig verarbeiten, haben Sie auch das Recht, sich bei der Datenschutzbehörde Ihres Mitgliedstaats oder der britischen Datenschutzbehörde zu beschweren.</p>
<p>Wenn Sie in der Schweiz ansässig sind, können Sie sich an den Eidgenössischen Datenschutz- und Öffentlichkeitsbeauftragten wenden.</p>

<p><strong>Rücknahme Ihrer Zustimmung:</strong><br> Wenn wir uns auf Ihre Zustimmung zur Verarbeitung Ihrer personenbezogenen Daten stützen, haben Sie das Recht, Ihre Zustimmung jederzeit zu widerrufen. Sie können Ihre Einwilligung jederzeit widerrufen, indem Sie sich mit uns in Verbindung setzen, indem Sie die Kontaktdaten im Abschnitt "WIE KÖNNEN SIE UNS ÜBER DIESEN HINWEIS KONTAKTIEREN?
Bitte beachten Sie jedoch, dass dies weder die Rechtmäßigkeit der Verarbeitung vor dem Widerruf noch die Verarbeitung Ihrer personenbezogenen Daten berührt, die im Vertrauen auf andere rechtmäßige Verarbeitungsgründe als die Einwilligung erfolgt.</p>

<p><strong>Konto-Informationen</strong><br>Sie können jederzeit die Informationen in Ihrem Konto überprüfen oder ändern oder Ihr Konto kündigen:
Melden Sie sich bei Ihren Kontoeinstellungen an und aktualisieren Sie Ihr Benutzerkonto. Wenn Sie Ihr Konto kündigen möchten, werden wir Ihr Konto und Ihre Informationen aus unseren aktiven Datenbanken deaktivieren oder löschen. Es kann jedoch sein, dass wir einige Informationen in unseren Dateien aufbewahren, um Betrug zu verhindern, Probleme zu beheben, bei Untersuchungen zu helfen, unsere rechtlichen Bestimmungen durchzusetzen und/oder geltende gesetzliche Vorschriften zu erfüllen.</p>
<p><strong>Cookies und ähnliche Technologien</strong><br>Die meisten Webbrowser sind so eingestellt, dass sie Cookies standardmäßig akzeptieren. Wenn Sie es vorziehen, können Sie Ihren Browser normalerweise so einstellen, dass er Cookies entfernt oder ablehnt. Wenn Sie sich dafür entscheiden, Cookies zu entfernen oder abzulehnen, kann dies bestimmte Funktionen und Dienste unserer Dienste beeinträchtigen. Sie können sich auch gegen interessensbasierte Werbung durch Werbetreibende in unseren Diensten entscheiden.</p>

<h2>Kontrollformular "Nicht verfolgen"-Funktionen</h2>
<p>Die meisten Webbrowser und einige mobile Betriebssysteme und Anwendungen enthalten eine "Do-Not-Track"-Funktion oder -Einstellung, die Sie aktivieren können, um zu signalisieren, dass Sie nicht möchten, dass Daten über Ihre Online-Browsing-Aktivitäten überwacht und gesammelt werden. Zum gegenwärtigen Zeitpunkt ist noch kein einheitlicher Technologiestandard für die Erkennung und Umsetzung von DNT-Signalen festgelegt worden. Daher reagieren wir derzeit nicht auf DNT-Browsersignale oder andere Mechanismen, die automatisch mitteilen, dass Sie nicht online verfolgt werden möchten. Sollte ein Standard für das Online-Tracking verabschiedet werden, den wir in Zukunft befolgen müssen, werden wir Sie in einer überarbeiteten Fassung dieses Datenschutzhinweises über diese Praxis informieren.</p>

<h2>Haben in Kalifornien ansässige Personen besondere Datenschutzrechte?</h2>
<p>Gemäß Abschnitt 1798.83 des kalifornischen Bürgerlichen Gesetzbuchs, auch bekannt als "Shine the light"-Gesetz, können unsere Nutzer, die in Kalifornien ansässig sind, einmal pro Jahr kostenlos Informationen über die Kategorien personenbezogener Daten (falls vorhanden), die wir zu Direktmarketingzwecken an Dritte weitergegeben haben, sowie die Namen und Adressen aller Dritten, mit denen wir im unmittelbar vorangegangenen Kalenderjahr personenbezogene Daten ausgetauscht haben, anfordern und von uns erhalten. Wenn Sie in Kalifornien ansässig sind und einen solchen Antrag stellen möchten, reichen Sie ihn bitte schriftlich bei uns ein, indem Sie die unten angegebenen Kontaktinformationen verwenden.</p>
<p>Wenn Sie unter 18 Jahre alt sind, Ihren Wohnsitz in Kalifornien haben und über ein registriertes Konto bei den Diensten verfügen, haben Sie das Recht, die Entfernung unerwünschter Daten zu verlangen, die Sie öffentlich in den Diensten veröffentlichen. Um die Entfernung solcher Daten zu beantragen, wenden Sie sich bitte an die unten angegebenen Kontaktinformationen und geben Sie die mit Ihrem Konto verknüpfte E-Mail-Adresse sowie eine Erklärung an, dass Sie in Kalifornien wohnen. Wir werden dafür sorgen, dass die Daten nicht öffentlich in den Diensten angezeigt werden. Bitte beachten Sie jedoch, dass die Daten möglicherweise nicht vollständig oder umfassend aus allen unseren Systemen (z. B. Backups usw.) entfernt werden.</p>

<h2>Werden wir diese Mitteilung aktualisieren?</h2>
<p>Wir können diesen Datenschutzhinweis von Zeit zu Zeit aktualisieren. Die aktualisierte Version wird durch einen entsprechenden Hinweis gekennzeichnet und tritt in Kraft, sobald sie zugänglich ist. Wenn wir wesentliche Änderungen an diesem Datenschutzhinweis vornehmen, können wir Sie entweder durch einen gut sichtbaren Aushang über diese Änderungen informieren oder Ihnen direkt eine Mitteilung zusenden. Wir empfehlen Ihnen, diesen Datenschutzhinweis regelmäßig zu lesen, um sich darüber zu informieren, wie wir Ihre Daten schützen.</p>

<h2>Wie können Sie uns bezüglich dieser Mitteilung kontaktieren?</h2>
<p>Wenn Sie Fragen oder Anmerkungen zu dieser Mitteilung haben, können Sie uns eine E-Mail an <a href="mailto:info@ferratec.ch" title="E-Mail senden">info@ferratec.ch</a> senden oder uns auf dem Postweg kontaktieren:<br><br>FERRATEC TECHNICS AG<br>Grossmattstrasse 19<br>8964 Rudolfstetten</p>

<h2>Wie können Sie die von uns gesammelten Daten einsehen, aktualisieren oder löschen?</h2>
<p>Je nach den in Ihrem Land geltenden Gesetzen haben Sie möglicherweise das Recht, Zugang zu den von uns gesammelten personenbezogenen Daten zu verlangen, diese Daten zu ändern oder zu löschen. Um die Überprüfung, Aktualisierung oder Löschung Ihrer persönlichen Daten zu beantragen, senden Sie bitte eine E-Mail an: <a href="mailto:info@ferratec.ch" title="E-Mail senden">info@ferratec.ch</a></p>
